config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  devise_for :users
  root to: "homes#top"

  resources :works do
    resource :work_favorite, only: [:create, :destroy]
    resources :work_comments, only: [:create, :destroy] do
      resource :thank, only: [:create, :destroy]
    end
  end
    get "works_art" => "works#works_art", as: "works_art"
    get "works_making" => "works#works_making", as: "works_making"
    get "works_memo" => "works#works_memo", as: "works_memo"

  resources :users, only: [:show, :index, :edit, :update] do
    resource :reletionships, only: [:create, :destroy]
    get "followings" => "reletionships#followings", as: "followings"
    get "followers" => "reletionships#followers", as: "followers"
    get "followwork" => "reletionships#followwork", as: "followwork"
    get "followart" => "reletionships#followart", as: "followart"
  end

    get "users/:id/users_art" => "users#users_art", as: "users_art"
    get "users/:id/users_making" => "users#users_making", as: "users_making"
    get "users/:id/users_memo" => "users#users_memo", as: "users_memo"

  resources :chats, only: [:show, :create, :destroy]
  resources :rooms, only: [:index]

  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/reletionship.rb
class Reletionship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
end

app/models/thank.rb
class Thank < ApplicationRecord
  belongs_to :user
  belongs_to :work_comment

  validates :user, uniqueness: {scope: :work_comment}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works, dependent: :destroy
  has_many :work_favorites, dependent: :destroy
  has_many :work_comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy

  has_many :thanks, dependent: :destroy

  has_many :user_rooms, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  has_many :reletionships, class_name: "Reletionship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_reletionships, class_name: "Reletionship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_reletionships, source: :follower
  has_many :followings, through: :reletionships, source: :followed

  has_one_attached :profile_image

  validates :name_id, uniqueness: true, presence: true
  validates :name, presence: true

  def follow(user)
    reletionships.create(followed_id: user.id)
  end

  def unfollow(user)
    reletionships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    else
      User.where('name LIKE?', '%' + content + '%')
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :work
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
  has_many :work_favorites, dependent: :destroy
  has_many :work_comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy

  has_one_attached :work_image

  validates :title, presence: true, if: :state_art?
  validates :work_image, presence: true, if: :state_art?
  validates :body, presence: true
  validates :state, presence: true

  def state_art?
    state == 'art'
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Work.where(body: content)
    else
      Work.where('body LIKE?', '%' + content + '%')
    end
  end

  def get_work_image(width, height)
    if work_image.attached?
      work_image.variant(resize_to_fit: [width, height]).processed
    else
      ''
    end
  end

  def work_favorited_by?(user)
    work_favorites.exists?(user_id: user.id)
  end

end

app/models/work_comment.rb
class WorkComment < ApplicationRecord
  belongs_to :user
  belongs_to :work

  has_many :thanks, dependent: :destroy

  validates :comment, presence: true

  def thanks_by?(user)
    thanks.exists?(user_id: user.id)
  end
end

app/models/work_favorite.rb
class WorkFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :work

  validates :user, uniqueness: {scope: :work}
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!
  before_action :block_non_related_users, only: [:show]
  before_action :set_new_work

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)
    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end

  def destroy
    @chat = current_user.chats.find(params[:id])
    @chat.destroy
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

  def block_non_related_users
    user = User.find(params[:id])
    unless current_user.following?(user) && user.following?(current_user)
      redirect_to request.referer
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_new_work

  def top
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
    before_action :authenticate_user!
    before_action :set_new_work

  def new
  end

  def create
    @work = Work.new(work_params)
    @work.user_id = current_user.id
    if @work.save
      flash[:notice] = "投稿しました"
      redirect_to request.referer
    else
      redirect_to request.referer
    end
  end

  def index
    @works = Work.all.order(id: :DESC)
  end

  def show
    @work = Work.find(params[:id])
    @new_work_comment = WorkComment.new
    unless ViewCount.find_by(user_id: current_user.id, work_id: @work.id)
      current_user.view_counts.create(work_id: @work.id)
    end
  end

  def works_art
    @works = Work.where(state: "art")
  end

  def works_making
    @works = Work.where(state: "making")
  end

  def works_memo
    @works = Work.where(state: "memo")
  end

  def edit
    @work = Work.find(params[:id])
  end

  def update
    @work = Work.find(params[:id])
    if @work.update(work_params)
      redirect_to work_path
    else
      render :edit
    end
  end

  def destroy
    @work = Work.find(params[:id])
    if @work.destroy
      flash[:notice] = "削除しました"
      redirect_to works_path
    else
      render :show
    end
  end

  private

  def work_params
    params.require(:work).permit(:state, :title, :body, :work_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/works/_form.html.erb
<%= form_with model: work do |f| %>
  <div class="form-group">
    <%= f.select :state, [["完成（全て入力）", "art"], ["制作過程（文章のみ必須）", "making"], ["制作メモ（文章のみ必須）", "memo"]], include_blank: "選択して下さい" %>
  </div>
  <div class="mb-3">
    <%= f.label :image %><br>
    <%= image_tag work.get_work_image(500,500) %>
    <%= f.file_field :work_image %>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit '投稿する', class: "btn btn-info" %>
  </div>
<% end %>

app/views/works/_index.html.erb
<% works.each do |work| %>
  <% if work.state == 'art' %>
    <%= link_to work_path(work) do %>
      <div class="card p-4 my-2 d-flex flex-row">
        <div class="col">
          <%= image_tag work.get_work_image(400,400) %>
        </div>
        <div class="col">
          <div class="font-weight-bold mb-3">
            <%= work.title %>
          </div>
          <div>
            <%= work.body %>
          </div>
          <div class="card-link text-right">
            <%= link_to user_path(work.user) do %>
              <div>
                <%= image_tag work.user.get_profile_image(50,50) %>
                <%= work.user.name %>
              </div>
              <div class="text-black-50">
                @<%= work.user.name_id %>
              </div>
            <% end %>
            <div class="text-black-50">
              <%= work.created_at %>
            </div>
            <div>
              <div>
                <%= render 'work_comments/count', work: work %>
              </div>
              <div class=<%= "favorite-" + work.id.to_s %>>
                <%= render 'work_favorites/btn', work: work %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <%= link_to work_path(work) do %>
      <div class="card p-4 my-2 d-flex flex-row">
        <div class="col">
          <%= image_tag work.get_work_image(400,400) %>
        </div>
        <div class="col">
          <%= work.body %>
          <div class="card-link text-right">
            <div>
              <%= image_tag work.user.get_profile_image(50,50) %>
              <%= work.user.name %>
            </div>
            <div class="text-black-50">
              @<%= work.user.name_id %>
            </div>
            <div class="text-black-50">
              <%= work.created_at %>
            </div>
            <div class=<%= "favorite-" + work.id.to_s %>>
              <%= render 'work_favorites/btn', work: work %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/works/_tab.html.erb
<div class="col card p-2 mx-1 <%= request.path.match("/works_art") ? "bg-info" : "" %>">
  <%= link_to works_art_path do %>
    <span class="<%= request.path.match("/works_art") ? "text-white" : "" %>">Art</span>
  <% end %>
</div>
<div class="col card p-2 mx-1 <%= request.path.match("/works_making") ? "bg-info" : "" %>">
  <%= link_to works_making_path do %>
    <span class="<%= request.path.match("/works_making") ? "text-white" : "" %>">Making</span>
  <% end %>
</div>
<div class="col card p-2 mx-1 <%= request.path.match("/works_memo") ? "bg-info" : "" %>">
  <%= link_to works_memo_path do %>
    <span class="<%= request.path.match("/works_memo") ? "text-white" : "" %>">Memo</span>
  <% end %>
</div>

app/views/works/edit.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-3 mx-auto">
      <p>投稿の編集</p>
      <%= render 'form', work: @work %>
    </div>
  </div>
</div>

app/views/works/index.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <h1>みんなの投稿一覧</h1>
      <%= render 'index', works: @works %>
    </div>
  </div>
</div>

app/views/works/new.html.erb
<div class="conteiner">
  <div class="row">
    <div class="col-md-3 mx-auto">
      <h1>新規投稿</h1>
      <%= render 'form', work: @work %>
    </div>
  </div>
</div>

app/views/works/show.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <p>投稿の詳細</p>
      <div class="card p-4 d-flex flex-row">
        <!--左側-->
        <div class="col-md-9">
          <%= image_tag @work.get_work_image(600,600), class: "card-img-top" %>
        </div>
        <!--右側-->
        <div class="col-md-3">
          <div>
            <h1 class="card-title"><%= @work.title %></h1>
          </div>
          <div>
            <p class="card-text"><%= @work.body %></p>
          </div>
          <!--ユーザー情報-->
          <div class="card-link text-right">
            <%= link_to user_path(@work.user_id) do %>
              <div>
                <%= image_tag @work.user.get_profile_image(50,50) %>
                <%= @work.user.name %>
              </div>
              <div class="text-black-50">
                @<%= @work.user.name_id %>
              </div>
            <% end %>
            <div class="text-black-50">
              <%= @work.created_at %>
            </div>
            <div>
              <!--コメント数-->
              <div class="work-comment-counter">
                <%= render 'work_comments/count', work: @work %>
              </div>
              <!--閲覧数-->
              <div>
                <%= @work.view_counts.count %> Views
              </div>
              <!--いいね数-->
              <div class=<%= "favorite-" + @work.id.to_s %>>
                <%= render 'work_favorites/btn', work: @work %>
              </div>
            </div>
            <!--投稿者の場合の編集ボタンと削除-->
            <% if @work.user == current_user %>
              <%= link_to edit_work_path(@work), class: "btn btn-outline-danger py-0" do %>
                <%= @work.state %>
              <% end %>
              <%= link_to '削除', work_path(@work), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-outline-secondary py-0" %>
            <% end %>
          </div>
          <!--コメント送信-->
          <div>
            <%= render 'work_comments/form', work: @work, new_work_comment: @new_work_comment %>
          </div>
          <!--コメント表示-->
          <div class="work-comment-index mt-3">
            <%= render 'work_comments/index', work: @work %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/works/works_art.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <h1>みんなのArt一覧</h1>
      <!--ART MAKING MEMOのタブ-->
      <div class="row">
        <%= render 'tab' %>
      </div>
      <%= render 'index', works: @works %>
    </div>
  </div>
</div>

app/views/works/works_making.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <h1>みんなのMaking一覧</h1>
      <!--ART MAKING MEMOのタブ-->
      <div class="row">
        <%= render 'tab' %>
      </div>
      <%= render 'index', works: @works %>
    </div>
  </div>
</div>

app/views/works/works_memo.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <h1>みんなのMemo一覧</h1>
      <!--ART MAKING MEMOのタブ-->
      <div class="row">
        <%= render 'tab' %>
      </div>
      <%= render 'index', works: @works %>
    </div>
  </div>
</div>