config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  devise_for :users
  root to: "homes#top"

  resources :works do
    resource :work_favorite, only: [:create, :destroy]
    resources :work_comments, only: [:create, :destroy] do
      resource :thank, only: [:create, :destroy]
    end
  end
    get "works_art" => "works#works_art", as: "works_art"
    get "works_making" => "works#works_making", as: "works_making"
    get "works_memo" => "works#works_memo", as: "works_memo"

  resources :users, only: [:show, :index, :edit, :update] do
    resource :reletionships, only: [:create, :destroy]
    get "followings" => "reletionships#followings", as: "followings"
    get "followers" => "reletionships#followers", as: "followers"
    get "followwork" => "reletionships#followwork", as: "followwork"
    get "followart" => "reletionships#followart", as: "followart"
  end

    get "users/:id/users_art" => "users#users_art", as: "users_art"
    get "users/:id/users_making" => "users#users_making", as: "users_making"
    get "users/:id/users_memo" => "users#users_memo", as: "users_memo"

  resources :chats, only: [:show, :create, :destroy]
  resources :rooms, only: [:index]

  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/reletionship.rb
class Reletionship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
end

app/models/thank.rb
class Thank < ApplicationRecord
  belongs_to :user
  belongs_to :work_comment

  validates :user, uniqueness: {scope: :work_comment}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works, dependent: :destroy
  has_many :work_favorites, dependent: :destroy
  has_many :work_comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy

  has_many :thanks, dependent: :destroy

  has_many :user_rooms, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  has_many :reletionships, class_name: "Reletionship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_reletionships, class_name: "Reletionship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_reletionships, source: :follower
  has_many :followings, through: :reletionships, source: :followed

  has_one_attached :profile_image

  validates :name_id, uniqueness: true, presence: true
  validates :name, presence: true

  def follow(user)
    reletionships.create(followed_id: user.id)
  end

  def unfollow(user)
    reletionships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    else
      User.where('name LIKE?', '%' + content + '%')
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :work
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
  has_many :work_favorites, dependent: :destroy
  has_many :work_comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy

  has_one_attached :work_image

  validates :title, presence: true, if: :state_art?
  validates :work_image, presence: true, if: :state_art?
  validates :body, presence: true
  validates :state, presence: true

  def state_art?
    state == 'art'
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Work.where(body: content)
    else
      Work.where('body LIKE?', '%' + content + '%')
    end
  end

  def get_work_image(width, height)
    if work_image.attached?
      work_image.variant(resize_to_fit: [width, height]).processed
    else
      ''
    end
  end

  def work_favorited_by?(user)
    work_favorites.exists?(user_id: user.id)
  end

end

app/models/work_comment.rb
class WorkComment < ApplicationRecord
  belongs_to :user
  belongs_to :work

  has_many :thanks, dependent: :destroy

  validates :comment, presence: true

  def thanks_by?(user)
    thanks.exists?(user_id: user.id)
  end
end

app/models/work_favorite.rb
class WorkFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :work

  validates :user, uniqueness: {scope: :work}
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!
  before_action :block_non_related_users, only: [:show]
  before_action :set_new_work

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)
    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end

  def destroy
    @chat = current_user.chats.find(params[:id])
    @chat.destroy
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

  def block_non_related_users
    user = User.find(params[:id])
    unless current_user.following?(user) && user.following?(current_user)
      redirect_to request.referer
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_new_work

  def top
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_new_work

  def index
    current_user_room_ids = current_user.user_rooms.pluck(:room_id)
    other_user_ids = UserRoom.where(room_id: current_user_room_ids)
                              .where.not(user_id: current_user.id)
                              .pluck(:user_id)
    @rooms_user = User.where(id: other_user_ids)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_new_work

  def show
    @user = User.find(params[:id])
    @works = @user.works.order(id: :DESC)
    @work = Work.new
  end

  def users_art
    @user = User.find(params[:id])
    @works = @user.works
    @work_state = @user.works.where(state: "art")
  end

  def users_making
    @user = User.find(params[:id])
    @works = @user.works
    @work_state = @user.works.where(state: "making")
  end

  def users_memo
    @user = User.find(params[:id])
    @works = @user.works
    @work_state = @user.works.where(state: "memo")
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "プロフィールを更新しました"
      redirect_to user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :name_id, :profile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/_mychat.html.erb
<div id="chat-<%= chat.id %>" class="text-right">
  <%= chat.message %>
  <%= image_tag chat.user.get_profile_image(70,70) %>
  <%= chat.user.name %>
  <%= link_to '削除', chat_path(chat), method: :delete, "data-confirm" => "本当に削除しますか？", remote: true, class: "btn btn-secondary p-1 m-2" %>
</div>

app/views/chats/create.js.erb
$('#chat_message').val("");
$('.message').append("<%= j(render 'chats/mychat', chat: @chat) %>");

app/views/chats/destroy.js.erb
$('#chat-<%= @chat.id %>').remove();

app/views/chats/show.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <p><%= @user.name %>さんとのDM</p>
      <div class="message">
        <% @chats.each do |chat| %>
          <div>
            <%= render 'layouts/errors', obj: @chat %>
            <% if chat.user == current_user %>
              <%= render 'mychat', chat: chat %>
            <% else %>
              <div>
                <%= image_tag chat.user.get_profile_image(70,70) %>
                <%= chat.user.name %>
                <%= chat.message %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <!--メッセージ送信フォーム-->
      <%= form_with model: @chat, local: false, class: "mt-3" do |f| %>
        <%= f.text_area :message, class: "form-control" %>
        <%= f.submit '送信', class: "btn btn-primary mt-2" %>
        <%= f.hidden_field :room_id %>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<% @rooms_user.each do |user| %>
  <% if current_user.following?(user) %>
    <div>
      <%= link_to chat_path(user) do %>
        <%= image_tag user.get_profile_image(70,70) %>
        <%= user.name %>とのDM
        <%= user.chats.last.message %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/users/_index.html.erb
<% users.each do |user| %>
<div class="card my-3 p-3">
  <div class="col">
    <%= link_to user_path(user) do %>
      <%= image_tag user.get_profile_image(70,70) %>
      <%= user.name %>
      @<%= user.name_id %>
    <% end %>
  </div>
  <div class="col">
    <%= user.profile %>
  </div>
</div>
<% end %>

app/views/users/_profile.html.erb
<h1><%= user.name %></h1>
<%= image_tag user.get_profile_image(100,100) %>
<%= user.name %>
@<%= user.name_id %>
<div>
  <%= user.profile %>
</div>
<div class="reletionships-count">
  <%= render 'reletionships/count', user: user %>
</div>
<% if current_user != user %>
  <!--フォローボタン-->
  <div class="reletionships-btn">
    <%= render 'reletionships/btn', user: user %>
  </div>
  <% if current_user.following?(user) && user.following?(current_user) %>
    <%= link_to 'DMを送る', chat_path(user.id) %>
  <% end %>
<% else %>
  <%= link_to 'プロフィール編集', edit_user_path, class: "btn btn-outline-danger py-0" %>
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, "data-confirm" => "ログアウトしますか？", class: "btn btn-outline-secondary py-0" %>
<% end %>

app/views/users/_tab.html.erb
<div class="col card p-2 mx-1 <%= request.path.match("/users_art") ? "bg-info" : "" %>">
  <%= link_to users_art_path do %>
    <span class="<%= request.path.match("/users_art") ? "text-white" : "" %>">Art（<%= works.where(state: "art").count %>）</span>
  <% end %>
</div>
<div class="col card p-2 mx-1 <%= request.path.match("/users_making") ? "bg-info" : "" %>">
  <%= link_to users_making_path do %>
    <span class="<%= request.path.match("/users_making") ? "text-white" : "" %>">Making（<%= works.where(state: "making").count %>）</span>
  <% end %>
</div>
<div class="col card p-2 mx-1 <%= request.path.match("/users_memo") ? "bg-info" : "" %>">
  <%= link_to users_memo_path do %>
    <span class="<%= request.path.match("/users_memo") ? "text-white" : "" %>">Memo（<%= works.where(state: "memo").count %>）</span>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-3 mx-auto">
      <p>投稿の編集</p>
      <%= form_with model: @user do |f| %>
        <%= render 'layouts/errors', obj: @user %>
        <div>
          <%= f.label :プロフィール画像 %><br>
          <%= f.file_field :profile_image, accept: 'image/*' %>
        </div>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :id %>
          <%= f.text_field :name_id, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :profile %>
          <%= f.text_area :profile, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit '編集', "data-confirm" => "編集を完了しますか？", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <p>ユーザーの一覧</p>
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <%= render 'profile', user: @user %>

      <!--ART MAKING MEMOのタブ-->
      <div class="row pt-3">
        <%= render 'tab', works: @works %>
      </div>
      <%= render 'works/index', works: @works %>
    </div>
  </div>
</div>

app/views/users/users_art.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <%= render 'profile', user: @user %>
      <!--ART MAKING MEMOのタブ-->
      <div class="row pt-3">
        <%= render 'tab', works: @works %>
      </div>
      <%= render 'works/index', works: @work_state %>
    </div>
  </div>
</div>

app/views/users/users_making.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <%= render 'profile', user: @user %>
      <!--ART MAKING MEMOのタブ-->
      <div class="row pt-3">
        <%= render 'tab', works: @works %>
      </div>
      <%= render 'works/index', works: @work_state %>
    </div>
  </div>
</div>

app/views/users/users_memo.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <%= render 'profile', user: @user %>
      <!--ART MAKING MEMOのタブ-->
      <div class="row pt-3">
        <%= render 'tab', works: @works %>
      </div>
      <%= render 'works/index', works: @work_state %>
    </div>
  </div>
</div>