config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  devise_for :users
  root to: "homes#top"

  resources :works do
    resource :work_favorite, only: [:create, :destroy]
    resources :work_comments, only: [:create, :destroy] do
      resource :thank, only: [:create, :destroy]
    end
  end
    get "works_art" => "works#works_art", as: "works_art"
    get "works_making" => "works#works_making", as: "works_making"
    get "works_memo" => "works#works_memo", as: "works_memo"

  resources :users, only: [:show, :index, :edit, :update] do
    resource :reletionships, only: [:create, :destroy]
    get "followings" => "reletionships#followings", as: "followings"
    get "followers" => "reletionships#followers", as: "followers"
    get "followwork" => "reletionships#followwork", as: "followwork"
    get "followart" => "reletionships#followart", as: "followart"
  end

    get "users/:id/users_art" => "users#users_art", as: "users_art"
    get "users/:id/users_making" => "users#users_making", as: "users_making"
    get "users/:id/users_memo" => "users#users_memo", as: "users_memo"

  resources :chats, only: [:show, :create, :destroy]
  resources :rooms, only: [:index]

  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/reletionship.rb
class Reletionship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
end

app/models/thank.rb
class Thank < ApplicationRecord
  belongs_to :user
  belongs_to :work_comment

  validates :user, uniqueness: {scope: :work_comment}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works, dependent: :destroy
  has_many :work_favorites, dependent: :destroy
  has_many :work_comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy

  has_many :thanks, dependent: :destroy

  has_many :user_rooms, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  has_many :reletionships, class_name: "Reletionship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_reletionships, class_name: "Reletionship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_reletionships, source: :follower
  has_many :followings, through: :reletionships, source: :followed

  has_one_attached :profile_image

  validates :name_id, uniqueness: true, presence: true
  validates :name, presence: true

  def follow(user)
    reletionships.create(followed_id: user.id)
  end

  def unfollow(user)
    reletionships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    else
      User.where('name LIKE?', '%' + content + '%')
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :work
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
  has_many :work_favorites, dependent: :destroy
  has_many :work_comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy

  has_one_attached :work_image

  validates :title, presence: true, if: :state_art?
  validates :work_image, presence: true, if: :state_art?
  validates :body, presence: true
  validates :state, presence: true

  def state_art?
    state == 'art'
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Work.where(body: content)
    else
      Work.where('body LIKE?', '%' + content + '%')
    end
  end

  def get_work_image(width, height)
    if work_image.attached?
      work_image.variant(resize_to_fit: [width, height]).processed
    else
      ''
    end
  end

  def work_favorited_by?(user)
    work_favorites.exists?(user_id: user.id)
  end

end

app/models/work_comment.rb
class WorkComment < ApplicationRecord
  belongs_to :user
  belongs_to :work

  has_many :thanks, dependent: :destroy

  validates :comment, presence: true

  def thanks_by?(user)
    thanks.exists?(user_id: user.id)
  end
end

app/models/work_favorite.rb
class WorkFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :work

  validates :user, uniqueness: {scope: :work}
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!
  before_action :block_non_related_users, only: [:show]
  before_action :set_new_work

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)
    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end

  def destroy
    @chat = current_user.chats.find(params[:id])
    @chat.destroy
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

  def block_non_related_users
    user = User.find(params[:id])
    unless current_user.following?(user) && user.following?(current_user)
      redirect_to request.referer
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_new_work

  def top
  end
end

app/controllers/reletionships_controller.rb
class ReletionshipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_new_work

  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)
    render 'replace_btn'
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(@user)
    render 'replace_btn'
  end

  def followings
    @user = User.find(params[:user_id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:user_id])
    @users = @user.followers
  end

  def followwork
    @user = User.find(params[:user_id])
    @works = Work.where(user_id: [current_user, *current_user.following_ids])
  end

  def followart
    @user = User.find(params[:user_id])
    @works = Work.where(user_id: [current_user, *current_user.following_ids], state: "art")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reletionships_helper.rb
module ReletionshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reletionships/_btn.html.erb
<% if current_user.following?(user) %>
  <%= link_to 'フォローを外す', user_reletionships_path(user), method: :delete, remote: true %>
<% else %>
  <%= link_to 'フォローする', user_reletionships_path(user), method: :post, remote: true %>
<% end %>

app/views/reletionships/_count.html.erb
<%= link_to user.followers.count, user_followers_path(user) %>フォロワー
<%= link_to user.followings.count, user_followings_path(user) %>フォロー

app/views/reletionships/followart.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <%= link_to user_path(@user) do %>
        ←<%= @user.name %>
        @<%= @user.name_id %>
      <% end %>
      <h2>フォロー中</h2>
      <%= render 'works/index', works: @works %>
    </div>
  </div>
</div>

app/views/reletionships/followers.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <%= link_to user_path(@user) do %>
        ←<%= @user.name %>
        @<%= @user.name_id %>
      <% end %>
      <h2>フォロワー</h2>
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/reletionships/followings.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <%= link_to user_path(@user) do %>
        ←<%= @user.name %>
        @<%= @user.name_id %>
      <% end %>
      <h2>フォロー中</h2>
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/reletionships/followwork.html.erb
<div class="conteiner px-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <%= link_to user_path(@user) do %>
        ←<%= @user.name %>
        @<%= @user.name_id %>
      <% end %>
      <h2>フォロー中</h2>
      <%= render 'works/index', works: @works %>
    </div>
  </div>
</div>

app/views/reletionships/replace_btn.js.erb
$('.reletionships-btn').html("<%= j(render 'reletionships/btn', user: @user) %>")
$('.reletionships-count').html("<%= j(render 'reletionships/count', user: @user) %>")