config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  devise_for :users
  root to: "homes#top"

  resources :works do
    resource :work_favorite, only: [:create, :destroy]
    resources :work_comments, only: [:create, :destroy] do
      resource :thank, only: [:create, :destroy]
    end
  end
    get "works_art" => "works#works_art", as: "works_art"
    get "works_making" => "works#works_making", as: "works_making"
    get "works_memo" => "works#works_memo", as: "works_memo"

  resources :users, only: [:show, :index, :edit, :update] do
    resource :reletionships, only: [:create, :destroy]
    get "followings" => "reletionships#followings", as: "followings"
    get "followers" => "reletionships#followers", as: "followers"
    get "followwork" => "reletionships#followwork", as: "followwork"
    get "followart" => "reletionships#followart", as: "followart"
  end

    get "users/:id/users_art" => "users#users_art", as: "users_art"
    get "users/:id/users_making" => "users#users_making", as: "users_making"
    get "users/:id/users_memo" => "users#users_memo", as: "users_memo"

  resources :chats, only: [:show, :create, :destroy]
  resources :rooms, only: [:index]

  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/reletionship.rb
class Reletionship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
end

app/models/thank.rb
class Thank < ApplicationRecord
  belongs_to :user
  belongs_to :work_comment

  validates :user, uniqueness: {scope: :work_comment}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works, dependent: :destroy
  has_many :work_favorites, dependent: :destroy
  has_many :work_comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy

  has_many :thanks, dependent: :destroy

  has_many :user_rooms, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  has_many :reletionships, class_name: "Reletionship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_reletionships, class_name: "Reletionship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_reletionships, source: :follower
  has_many :followings, through: :reletionships, source: :followed

  has_one_attached :profile_image

  validates :name_id, uniqueness: true, presence: true
  validates :name, presence: true

  def follow(user)
    reletionships.create(followed_id: user.id)
  end

  def unfollow(user)
    reletionships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    else
      User.where('name LIKE?', '%' + content + '%')
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :work
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
  has_many :work_favorites, dependent: :destroy
  has_many :work_comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy

  has_one_attached :work_image

  validates :title, presence: true, if: :state_art?
  validates :work_image, presence: true, if: :state_art?
  validates :body, presence: true
  validates :state, presence: true

  def state_art?
    state == 'art'
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Work.where(body: content)
    else
      Work.where('body LIKE?', '%' + content + '%')
    end
  end

  def get_work_image(width, height)
    if work_image.attached?
      work_image.variant(resize_to_fit: [width, height]).processed
    else
      ''
    end
  end

  def work_favorited_by?(user)
    work_favorites.exists?(user_id: user.id)
  end

end

app/models/work_comment.rb
class WorkComment < ApplicationRecord
  belongs_to :user
  belongs_to :work

  has_many :thanks, dependent: :destroy

  validates :comment, presence: true

  def thanks_by?(user)
    thanks.exists?(user_id: user.id)
  end
end

app/models/work_favorite.rb
class WorkFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :work

  validates :user, uniqueness: {scope: :work}
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!
  before_action :block_non_related_users, only: [:show]
  before_action :set_new_work

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)
    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end

  def destroy
    @chat = current_user.chats.find(params[:id])
    @chat.destroy
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

  def block_non_related_users
    user = User.find(params[:id])
    unless current_user.following?(user) && user.following?(current_user)
      redirect_to request.referer
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <%= obj.errors.count %>件の必須項目が入力されていません
  <ul>
    <% obj.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artwork</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/d3818fb7f0.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダー-->
    <header class="fixed-top" style="height:50px; background-color: #d4ebec;" >
      <div class="contener">
        <div class="row">
          <div class="col d-flex justify-content-center py-2">
            <% if user_signed_in? %>
            <div class="col-md-4">
              <%= render 'searches/form' %>
            </div>
            <div class="col-md-8">
              <%= link_to '投稿する', new_work_path, class: "modal-open px-3" %>
              <%= link_to 'みんなの作品', works_path, class: "px-3" %>
              <%= link_to 'マイページ', user_path(current_user.id), class: "px-3" %>
              <%= link_to current_user.name + 'さんのDM', rooms_path, class: "px-3" %>
            </div>
            <% else %>
              <%= link_to 'ログイン', new_user_session_path %>
            <% end %>
          </div>
        </div>
      </div>
    </header>
    <!--フラッシュメッセージ-->
    <%= flash[:notice] %>
    <main>
      <%#= render 'layouts/errors', obj: @new_work %>
      <div class="contener py-5">
      <%= yield %>
      </div>
    </main>
    <!--フッター-->
    <footer class="fixed-bottom" style="height:50px; background-color: #d4ebec;">
      <div class="contener">
        <div class="row">
          <div class="col d-flex justify-content-center py-2">
            <% if user_signed_in? %>
              <%= link_to 'フォロー中の投稿', user_followwork_path(current_user.id), class: "px-3" %>
              <%= link_to 'フォロー中の作品', user_followart_path(current_user.id), class: "px-3" %>
              <%= link_to '検索', new_work_path, class: "px-3" %>
              <%= link_to '(通知)　', new_work_path, class: "px-3" %>
              <%= link_to 'マイページ　', user_path(current_user.id), class: "px-3" %>
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, "data-confirm" => "ログアウトしますか？", class: "px-3" %>
            <% else %>
              <%= link_to 'ログイン', new_user_session_path %>
            <% end %>
          </div>
        </div>
      </div>
    </footer>

    <!--投稿フォーム（モーダル）-->
    <div class="modal-container">
    </div>
    <div class="modal-body">
      <div class="modal-close"><i class="fa-solid fa-circle-xmark"></i></div>
      <div class="modal-post-content">
        <% if user_signed_in? %>
          <%= render 'works/form', work: @new_work %>
        <% end %>
      </div>
    </div>

  </body>
</html>